# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clip_polygon_to_bbox <- function(coords, xmin, xmax, ymin, ymax) {
    .Call(`_ppmData_clip_polygon_to_bbox`, coords, xmin, xmax, ymin, ymax)
}

deltri_cpp <- function(coords) {
    .Call(`_ppmData_deltri_cpp`, coords)
}

dirtess_poly_area <- function(x, y) {
    .Call(`_ppmData_dirtess_poly_area`, x, y)
}

dirtess_cpp <- function(coords) {
    .Call(`_ppmData_dirtess_cpp`, coords)
}

matrices_to_polygons <- function(matrices) {
    .Call(`_ppmData_matrices_to_polygons`, matrices)
}

dirtess_clip_areas_cpp <- function(coords, ncoords, parts_outer_x, parts_outer_y, parts_hole_x_list, parts_hole_y_list) {
    .Call(`_ppmData_dirtess_clip_areas_cpp`, coords, ncoords, parts_outer_x, parts_outer_y, parts_hole_x_list, parts_hole_y_list)
}

dirtess_clip_cpp <- function(coords, ncoords, parts_outer_x, parts_outer_y, parts_hole_x_list, parts_hole_y_list) {
    .Call(`_ppmData_dirtess_clip_cpp`, coords, ncoords, parts_outer_x, parts_outer_y, parts_hole_x_list, parts_hole_y_list)
}

