# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

deltri_cpp <- function(coords) {
    .Call(`_ppmData_deltri_cpp`, coords)
}

dirtess_poly_area <- function(x, y) {
    .Call(`_ppmData_dirtess_poly_area`, x, y)
}

dirtess_cpp <- function(coords) {
    .Call(`_ppmData_dirtess_cpp`, coords)
}

